version: "3.8"

services:
  api:
    image: echoes-backend:latest
    ports:
      - "5000:80"
    secrets:
      - google_maps_api_key
      - gemini_api_key
      - app_name
      - environment
      - debug
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - echoes-network

  frontend:
    image: echoes-frontend:latest
    ports:
      - "3000:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - echoes-network

secrets:
  google_maps_api_key:
    external: true
  gemini_api_key:
    external: true
  app_name:
    external: true
  environment:
    external: true
  debug:
    external: true

networks:
  echoes-network:
    driver: overlay
